### ISSUE TITLE
how to get data from bootstrap table with pagination

### ISSUE THREAD

**Issue by mayurpande** [afourmy/flask-gentelella#4]
I am looking on the datatables website, but not sure how to integrate into the flask-gentelella

**Comment by afourmy** [comment]
I'm using jquery to populate the datatable, as well as edit/delete rows.

Code for the initialization of the datatable: https://github.com/afourmy/eNMS/blob/master/eNMS/objects/static/poolManagement.js#L4-L26

Code to edit/delete a row: 
https://github.com/afourmy/eNMS/blob/master/eNMS/objects/static/poolManagement.js#L79-L106

Result = something like that
http://afourmy.pythonanywhere.com/objects/object_management
Note that this is a demo website, so if you delete a row from the datatable, it is deleted on the front-end (from the table, graphically) but if you reload the page, the row will still be here because I don't delete it in the back-end (same for the editing of a row).
