### ISSUE TITLE
Why do I have to GET twice each time I refresh the page?

### ISSUE THREAD

**Issue by TangDY** [afourmy/flask-gentelella#5]
Why do I have to GET twice each time I refresh the page?

127.0.0.1 - - [26/Jul/2018 15:35:38] "GET /home/index HTTP/1.1" 200 -
127.0.0.1 - - [26/Jul/2018 15:35:38] "GET /home/index HTTP/1.1" 200 -
127.0.0.1 - - [26/Jul/2018 15:35:51] "GET /home/index HTTP/1.1" 200 -
127.0.0.1 - - [26/Jul/2018 15:35:51] "GET /home/index HTTP/1.1" 200 -
127.0.0.1 - - [26/Jul/2018 15:36:13] "GET /home/index2 HTTP/1.1" 200 -
127.0.0.1 - - [26/Jul/2018 15:36:13] "GET /home/index2 HTTP/1.1" 200 -

**Comment by afourmy** [comment]
If you're running in debug mode, Flask is initialized twice ( https://stackoverflow.com/questions/9449101/how-to-stop-flask-from-initialising-twice-in-debug-mode )

**Comment by TangDY** [comment]
thanks @afourmy , But I turned off debug mode, the problem is still, still have to GET twice.

**Comment by TangDY** [comment]
* Serving Flask app "gentelella.py"
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: off

127.0.0.1 - - [30/Jul/2018 12:00:04] "GET /forms/form HTTP/1.1" 200 -
127.0.0.1 - - [30/Jul/2018 12:00:04] "GET /forms/form HTTP/1.1" 200 -
127.0.0.1 - - [30/Jul/2018 12:00:11] "GET /forms/form HTTP/1.1" 200 -
127.0.0.1 - - [30/Jul/2018 12:00:11] "GET /forms/form HTTP/1.1" 200 -

**Comment by afourmy** [comment]
@TangDY This is because of the following line: https://github.com/afourmy/flask-gentelella/blob/master/app/base/templates/base_site.html#L8
Gentelella does not have a `favicon.ico`, thus raising at each page the following error: `127.0.0.1 - - [31/Jul/2018 14:26:38] "GET /favicon.ico HTTP/1.1" 404 -`.
In order to prevent this, I added the line `<link rel="shortcut icon" href="#" />` which triggers a GET request to the current page (`<link rel="shortcut icon" href="" />` does not work).
Ideally, you should replace `#` with a link to your `favicon.ico`, if you have one, and the double GET behavior will disappear. If you just remove this line, instead of two GET, you will have one GET and one 404 error.

**Comment by afourmy** [comment]
I just committed a favicon, it should fix your issue: https://github.com/afourmy/flask-gentelella/commit/eaaa436ac256391cf67df73f6160227b527b309d

Can you test again and confirm that it is working for you ?
Note that my first remark about Flask being initialized twice in debug mode is still valid: one for the application and one for the reloader, so you should have 2 GET in debug mode, and 1 GET only in production mode)

**Comment by TangDY** [comment]
@afourmy Thanks, the problem has been fixed, I ignored the 404 error.
