### ISSUE TITLE
error in executing 

### ISSUE THREAD

**Issue by ayockishaya** [afourmy/flask-gentelella#9]
when ever i execute on my windows 10  i get 

Error: Detected factory "create_app" in module "app", but could not call it without arguments. Use "FLASK_APP='app:create_app(args)'" to specify arguments.

**Comment by afourmy** [comment]
@ayockishaya how exactly are you executing the application ? have you followed the installation instructions of the readme ?

**Comment by siparker** [comment]
He was trying to start a migration. i am having the same probelm discovering the right format to use.

Using Flask-Migrate you type `flask db init` to create a new migration. however because this project is using an app factory "create_app" it wont allow this to run without arguments.

On windows i have tried various things `set GENTELELLA_CONFIG_MODE=Debug` and then `flask db init Flask_App=app:create_app(config_mode)` but without any success. 

Could you let me know what the normal process is of creating a new migration within flask-gentellela. 

for me it is within windows10 using powershell as command line

**Comment by siparker** [comment]
I must be missing a setting somewhere. 

`PS G:\Dev Root\2019\flask-gentelella> set FLASK_APP=gentelella.py
PS G:\Dev Root\2019\flask-gentelella> flask db migrate
Usage: flask db migrate [OPTIONS]

Error: Detected factory "create_app" in module "app", but could not call it without arguments. Use "FLASK_APP='app:create_app(args)'" to specify arguments.
PS G:\Dev Root\2019\flask-gentelella>
`
Are there any other steps I might be missing?

**Comment by afourmy** [comment]
Not that I know of.
Perhaps an environment / version issue.
Try deleting the "migrations" folder, then recreate it with "flask db
init", and then "flask db migrate"

**Comment by afourmy** [comment]
thanks, I added the powershell syntax in the readme

**Comment by Clarmy** [comment]
Similar problem.

This can't work and raise the same error : 
```python
from flask import Flask


from app.settings import envs  # noqa
from app.ext import init_ext  # noqa


def create_app(env):
    """初始化app"""
    print(env)
    app = Flask(__name__)
    config = envs.get(env)
    app.config.from_object(config)
    init_ext(app)
    with app.app_context():
        from app.apis.routes import generate_routes
        generate_routes(app)

    return app
```

While if I give a default value for `env`, it works:

```python
from flask import Flask


from app.settings import envs  # noqa
from app.ext import init_ext  # noqa


def create_app(env="develop"):
    """初始化app"""
    print(env)
    app = Flask(__name__)
    config = envs.get(env)
    app.config.from_object(config)
    init_ext(app)
    with app.app_context():
        from app.apis.routes import generate_routes
        generate_routes(app)

    return app
```
